name: CD

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/setup-node@v4
        name: Setup Node
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/
      - run: yarn install --frozen-lockfile
        name: Yarn Install
      - run: yarn test
        name: Test
      # - run: yarn publish
      #   name: Publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
      - uses: sergeysova/jq-action@v2
        name: Derive Version
        id: version
        with:
          cmd: 'jq .version package.json -r'
      - uses: elgohr/Github-Release-Action@v5
        name: Create Tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release ${{ steps.version.outputs.value }}
          tag: ${{ steps.version.outputs.value }}